[package]
name = "coinstream"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
tungstenite = { version = "0.24", features = ["native-tls"] }
serde_json = "1.0"
eframe = "0.29"
egui_plot = "0.29"
serde = { version = "1.0", features = ["derive"] }